name: Update Top Languages

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch GitHub Stats
        run: |
          curl -o top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=graceannaakparanta&layout=pie&count_private=true&token=${{ secrets.STATS_TOKEN }}"

      - name: Commit and Push Changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}  # Using the correct secret
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@https://github.com/GraceAnnaAkparanta/GraceAnnaAkparanta
          git add top-langs.svg
          git commit -m "Updated Top Languages" || echo "No changes to commit"
          git push origin main
